### ISSUE TITLE
Controller input device fails to register after resume

### ISSUE THREAD

**Issue by andyschmid** [dlundqvist/xone#132]
I believe commit #118 introduced a regression, there is a race condition on resume where the controller may not fully register the input device. 

If I wake the system from sleep using the gamepad, the input device is never registered by the xone driver.
However, if I wake the system another way (power button, keyboard, etc) and turn on the controller after the system has resumed, the input device is properly registered and the controller functions has expected.

[dmesg_failure.txt](https://github.com/user-attachments/files/23397665/dmesg_failure.txt)

Initial successful connection of gamepad:
```
[  226.729305] input: Microsoft Xbox Controller as /devices/pci0000:00/0000:00:08.1/0000:0d:00.4/usb5/5-2/5-2:1.0/gip0/gip0.0/input/input32
[  226.729401] xone-gip-gamepad gip0.0: gip_register_client: registered
....
[  227.266083] xone-gip gip0: gip_send_pkt_simple: cmd=0x06 len=0x0006 seq=0x0e offset=0x0000
[  227.281417] xone_dongle_handle_event: XONE_DONGLE_EVT_ENABLE_ENCRYPTION
[  227.281422] xone-dongle 5-2:1.0: xone_dongle_enable_client_encryption: wcid=1, address=7e:ed:83:25:08:49
[  228.262114] input: Microsoft X-Box 360 pad 0 as /devices/virtual/input/input33
```

After resume note missing "input: Microsoft X-Box 360 pad 0"
```
[  239.580169] input: Microsoft Xbox Controller as /devices/pci0000:00/0000:00:08.1/0000:0d:00.4/usb5/5-2/5-2:1.0/gip0/gip0.0/input/input34
...
[  240.111689] xone_dongle_handle_event: XONE_DONGLE_EVT_ENABLE_ENCRYPTION
[  240.111695] xone-dongle 5-2:1.0: xone_dongle_enable_client_encryption: wcid=1, address=7e:ed:83:25:08:49
```

I've tested reverting #118 and have confirmed this resolves the issue.

[dmesg_118_reverted_fixed.txt](https://github.com/user-attachments/files/23397881/dmesg_118_reverted_fixed.txt)

@Lawstorant Its not clear to me why the gip_gamepad_init_input() call was moved by this change, could you explain the reason for this? Can #118 be reverted/fixed? Thanks!

**Comment by andyschmid** [comment]
I forgot to mention this appears to be hardware dependent. I have an older AM4 system that does not exhibit this issue but my newer AM5 system runs into this almost every time.. leading me to believe it is related to timing.

**Comment by Lawstorant** [comment]
Yes, there are several issues I can't reproduce on my AM4 system with X570 chipset and since not much real testing can be done, some things wait for people like you :D

I remember moving this back for some reason, I'll try to remember but something was definately broken.

**Comment by Lawstorant** [comment]
Unfortunately, some discussions happen on discord and are hard to discover :/ Still, I found the reason for this change (I should've explained it in PR, I think I forgot).

<img width="1572" height="438" alt="Image" src="https://github.com/user-attachments/assets/dc086ec6-49f5-41c1-83d9-5cd6df234e04" />

**Comment by Lawstorant** [comment]
I have a weird idea to maybe work around this and not reintroduce that issue.

**Comment by andyschmid** [comment]
Reverting #118 might not be the real solution (it could just happen to work in my case), but the problem I'm seeing sounds similar to what was described in that discord discussion.

Next I was planning on adding some kprint traces to try and see what is going on.

**Comment by Lawstorant** [comment]
Yeah, just simple `pr_debug()` will be enough. There's a nice `test` make target for testing so you won't have to reinstall etc.

I think more debugs in `gip_gamepad_probe()` could help. I must say this SOMETIMES happens on my old dongle.

**Comment by Lawstorant** [comment]
I added some things in this new PR, would you like to test it? I think a 3 second delay is okay, but I might lower it to 2 seconds.

After sitting in my rig, I actually had the same issue. After waking the computer with my Elite 2, it wasn't doing anything, but waking with anything else was fine. Unfortunately, even just restarting my computer made it go away so yeah, something about the hardware.

**Comment by Lawstorant** [comment]
I was even thinking of just straight up resetting the whole dongle after resume, at least controllers will reconnect without issues so why not :D

**Comment by andyschmid** [comment]
Happy to test the PR. 

I was also trying to understand the initialization/resume flow. Looks like there are a few asynchronous tasks executed which could be completing out of the expected order. This may or may not matter depending if following operations depend on these tasks completing (i.e. authentication/encryption setup).

**Comment by andyschmid** [comment]
PR #133 tested fine on my system. Put the system through a sleep->resume cycle a few times and the controller worked every time.

[dmesg_try_something.txt](https://github.com/user-attachments/files/23403388/dmesg_try_something.txt)

I'm not sure how to test the autosuspend function, is there a way to trigger this?

**Comment by Lawstorant** [comment]
Just waiting. When I had to test it, I just lowered it to something like 5 seconds. It's `XONE_DONGLE_SUSPEND_DELAY`. It's triggered by the system itself

**Comment by Lawstorant** [comment]
I updated the PR and removed input init after authentication. It's not the place for that either way. It's not a perfect fix, I'd like to understand the underlying issue as well.

We know one thing, if the input didn't register, it means we never reached `gip_gamepad_init_input()` or even `gip_init_input()`. I don't think the whole probe would be skipped so something along the probe failed.

How about adding some debugs at every stage of gamepad probe? I just worry that something as stupid as adding debug prints could hide this.

I updated the PR + added a `wihout-sleep` branch shich has debug prints in the gamepad probe, but no sleeps in the dongle resume.

**Comment by andyschmid** [comment]
The updated PR (344dc2d757c185e5717a0b4a73247caa6737fd71) doesn't fix the problem on my system.

The controller is unresponsive after resume:
[dmesg_try_something2.txt](https://github.com/user-attachments/files/23403576/dmesg_try_something2.txt)

**Comment by Lawstorant** [comment]
Ugh, I'm stupid and I didn't push the commit with more debugs to the PR branch. Could you post dmesg with driver from without-sleep branch if it isn't too much to ask?

Weirdly enough, I can see the inpit init debugs after sleep so it seems that at least it's trying to init, I just don't know why it fails.

Hmm, maybe it fails at register device so everything IS set up, just the registering that fails?

**Comment by andyschmid** [comment]
Here is the output from the without-sleep branch (76171680ba20988c027d75b8c4128eeab209d002): 

[dmesg_without-sleep.txt](https://github.com/user-attachments/files/23406641/dmesg_without-sleep.txt)

**Comment by andyschmid** [comment]
I did some tracing of my own and found something interesting. Looking at a trace of Pre-suspend and Post-suspend, the order which `gip_register_client()` is called differs.

<img width="1703" height="1200" alt="Image" src="https://github.com/user-attachments/assets/d24e7f8d-1bad-4d0f-b80f-37afc1ad326a" />

I suspect the issue is on resume `gip_register_client()` is getting called prior to `gip_gamepad_probe()`, so the device is never properly registered with the kernel. 

I've uploaded both dmesg traces: 
[pre_trace.txt](https://github.com/user-attachments/files/23407666/pre_trace.txt)
[post_trace.txt](https://github.com/user-attachments/files/23407665/post_trace.txt)

**Comment by Lawstorant** [comment]
Thanks very much! I'll dig into this as well but feel free to post any PRs if you come up with something. I must say, I'm not super familiar with the codebase myself, I mainly fix and improve what I can and keep this working with newer kernels.

**Comment by Lawstorant** [comment]
Well, `gip_gamepad_init_input()` does `input_register_device(dev)` at the end so it should be registered.

**Comment by andyschmid** [comment]
I'm reading up on how linux driver code functions, the interaction between gip and gip-gamepad code is a bit hard to follow.

I feel like there is code in this driver that is dependent on specific timing, and so far has just worked for the most part.

Additionally now my controller turns off right away after waking the system, odd change in behavior..
edit: this was due to low battery.. user error

**Comment by Lawstorant** [comment]
My best guess is that the gip client thing and gamepad thing were thought of as separate, and for the most part DO look separate but like you said, something is not always right. I'm thinking of a way to force the bad behavior, I might just add a one second sleep to the input init and see if registering earlier is the culprit. I guess we could add a loop waiting for the input init to finish first IF the device is a gamepad.

**Comment by Lawstorant** [comment]
Okay! I think I have at least a little progress. I did my own debugs and I think what you compared is not the same thing. The "register before gamepad probe" is a bit unrelated since it's the register for the dongle itself, which must happen first and after sleep. I think it was just buried somewhere earlier in the "working" dmesg.

What is more important is that I think, the register was never actually triggered. Look at your own traces, the register after gamepad probe starts with `xone-gip-gamepad` but the one on the right starts with just `xone-gip`. Or maybe it just lost the context

**Comment by andyschmid** [comment]
A bit more experimenting... 

I added a delay in `gip_register_client()` and this seems to resolve the timing issue. 500ms delay works, going down to 100ms does not.

I think the race condition here is between `gip_gamepad_probe()` and `gip_register_client()`, both are executed asynchronously. In cases where `gip_gamepad_probe()` occurs after `gip_register_client()` the controller fails.

**Comment by andyschmid** [comment]
> Look at your own traces, the register after gamepad probe starts with `xone-gip-gamepad` but the one on the right starts with just `xone-gip`.

I noticed this as well, was confused as to the difference. It is the same function, but the debug output lists xone-gip or xone-gip-gamepad depending on the timing

**Comment by Lawstorant** [comment]
Oooh okay, some maybe `gip_register_client()` needs some context from the `gip_gamepad_probe()` and if it's not present, it fails somehow?

**Comment by Lawstorant** [comment]
Hmm, I'm thinking if a way to resolve it better than just a `msleep()` :P Though you'll be surprised how many crucial sleeps are in the intel wireless firmware

Still, that would make sense since gamepad init is dependent on kernel and gip client register is just a scheduled work. I can easily see how they could sometimes be scheduled differently

I'm now digging into `client->dev.type = &gip_client_type;`

**Comment by andyschmid** [comment]
> Hmm, I'm thinking if a way to resolve it better than just a `msleep()` :P Though you'll be surprised how many crucial sleeps are in the intel wireless firmware

I agree, adding a delay is just masking the root cause. Was more just testing with it to validate my suspicions.

> Still, that would make sense since gamepad init is dependent on kernel and gip client register is just a scheduled work. I can easily see how they could sometimes be scheduled differently

I think the probe functions are triggered by the device interrupts. I'm wondering if in my case the `gip_gamepad_probe()` call is delayed for some reason.

**Comment by Lawstorant** [comment]
USB is very fickle so yeah, probably. I had a lot of issues when fixing reset routines as well because of the multiple ways a USB hub can act when the PC is asleep. My X570s Aero G is quite good and USB hubs work perfectly but some motherboards completely cut off power.

**Comment by Lawstorant** [comment]
Okay yeah, I think I'm now 100% confident you're right. Register function calls `device_register(&client->dev)` but gamepad probe does `devm_kzalloc(&client->dev, sizeof(*gamepad), GFP_KERNEL)` so IDK what kernel is registering, but sure as hell something quite empty :D

I wonder though, something must be initialized there since the register function is assigning parent, type and bus structs and the struct wouldn't be allocated yet. I'd expect an oops.

**Comment by Lawstorant** [comment]
Okay `gip_get_client` does kzalloc for the whole `struct gip_client *client` and that struct contains `struct device dev` (note that this isn't a pointer).

**Comment by Lawstorant** [comment]
Maybe, just maybe we're barking at the wrong tree. I just replicated the issue forcibly by removing `err = input_register_device(dev);` from `gip_gamepad_init_input`.

Nah, removing register from client does the same thing.

**Comment by Lawstorant** [comment]
What if we just waited for `client->dev.driver_data` to be populated?

**Comment by Lawstorant** [comment]
Okay, I think it's only the messages that came in a different order. `gip_gamepad_probe` isn't triggered before `device_register(&client->dev)` in `gip_register_client`. So registoering the client first is a must, then the registered client is detected as a gamepad by the kernel.

**Comment by andyschmid** [comment]
I believe you are correct, but its odd adding a delay there resolves the issue for me. I don't quite understand that yet

**Comment by Lawstorant** [comment]
At this point, I can only think that it's something in the firmware. Maybe it doesn't have some data at this point because reasons. Maybe after sleep, without full init, it's just not ready

**Comment by Lawstorant** [comment]
I went down the stack and got down to processing frames on the wireless adapter. I don't think I'll find anything useful there.

I created a new PR with the delay here: https://github.com/dlundqvist/xone/pull/134

If this works for you, I'll merge it and push a new release

**Comment by andyschmid** [comment]
I made a couple comments on the PR. Tested it on my machine and its works, that's not to say its going to fix all situations but might be a good enough for now.
